# ====== Metadata ======
id: 977e1eb2-ebe8-4fac-8def-da47f62ea8eb
name: WebApplicationFirewallEnabled
description: This rule assesses whether an [LoadBalancer] that offers the property [webApplicationFirewall], has [p1:enabled] configured correctly.
category: NetworkSecurity
version: "v1" 
comments: The Web Application Firewall (WAF) protects web applications by filtering and monitoring HTTP traffic. It defends against threats like SQL injection and cross-site scripting, enhancing overall application security.
# ====== Configuration ======
configuration:
  p1:
    operator: "=="
    targetValue: true